In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import LinearSVC
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

train = pd.read_csv("dataGameWonMoreThan1500WithColumnNames.csv")
# response = pd.read_csv("dataGameWonMoreThan1500WithColumnNames.csv")
train = pd.get_dummies(train)
# train.shape
train.head()



Unnamed: 0  ghostUp  ghostDown  ghostLeft  ghostRight  wallUp  wallDown  \
0         261    False      False      False       False    True      True   
1         262    False      False      False       False    True      True   
2         263    False      False      False       False    True      True   
3         264    False      False      False       False   False      True   
4         265    False      False      False       False    True      True   

   wallLeft  wallRight  foodUp  ...  nearestFood  nearestGhost  \
0     False      False   False  ...          1.0      0.066667   
1     False      False   False  ...          0.5      0.076923   
2     False      False   False  ...          0.5      0.090909   
3     False      False    True  ...          1.0      0.142857   
4     False      False   False  ...          0.5      0.142857   

   nearestCapsule  legalPositionUp  legalPositionDown  legalPositionULeft  \
0        0.083333            False              False                True   
1        0.090909            False              False                True   
2        0.111111            False              False                True   
3        0.166667             True              False                True   
4        0.166667            False              False                True   

   legalPositionRight  pacmanPositionX  pacmanPositionY  labelNextAction  
0                True             0.45         0.142857                2  
1                True             0.40         0.142857                2  
2                True             0.35         0.142857                2  
3                True             0.30         0.142857                2  
4                True             0.25         0.142857                2  

[5 rows x 27 columns]

In [2]:
X = train.drop('labelNextAction', axis=1)
y = train['labelNextAction']

# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
print("En route vers l'entrainement...")

En route vers l'entrainement...


In [3]:
# # Polynomial Kernel
# from sklearn.svm import SVC
# svclassifier = SVC(kernel='poly', degree=8)
# svclassifier.fit(X_train, y_train)
# print("L'entrainement est terminé !")

In [4]:
# Training the Algorithm
# from sklearn.svm import SVC
# svclassifier = SVC(kernel='linear')
# svclassifier.fit(X_train, y_train)
# print("L'entrainement est terminé !")

In [5]:
# y_pred = svclassifier.predict(X_test)
# print("Une prédiction ?")

In [6]:
# from sklearn.metrics import classification_report, confusion_matrix
# print(confusion_matrix(y_test,y_pred))
# print(classification_report(y_test,y_pred))

# Gaussian Kernel

In [7]:
# train = pd.read_csv("dataGameWonMoreThan1500WithColumnNames.csv")
# # response = pd.read_csv("dataGameWonMoreThan1500WithColumnNames.csv")
# train = pd.get_dummies(train)
# # train.shape
# train.head()


In [8]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)
print("Go vers la prédiction et l'évaluation...")


E:\Users\Mohamed\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Go vers la prédiction et l'évaluation...


In [9]:
y_pred = svclassifier.predict(X_test)
print("Oh tu mets cuit")

Oh tu mets cuit


In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 61   2  39  35]
 [  3  79  29  32]
 [  7   5 348  18]
 [  5  15  15 326]]
              precision    recall  f1-score   support

           0       0.80      0.45      0.57       137
           1       0.78      0.55      0.65       143
           2       0.81      0.92      0.86       378
           3       0.79      0.90      0.84       361

    accuracy                           0.80      1019
   macro avg       0.80      0.71      0.73      1019
weighted avg       0.80      0.80      0.79      1019



# Sigmoid Kernel

In [11]:
# from sklearn.svm import SVC
# svclassifier = SVC(kernel='sigmoid')
# svclassifier.fit(X_train, y_train)
# print("Donc là on spécifie le sigmoid au Kernel pour voir ce que ça donne...")

In [12]:
# y_pred = svclassifier.predict(X_test)
# print("T'y crois toi ?")

In [13]:
# from sklearn.metrics import classification_report, confusion_matrix
# print("Aller vasy j'suis chaud")
# print(confusion_matrix(y_test, y_pred))
# print(classification_report(y_test, y_pred))